import * as fs from "fs";
import * as path from "path";
import type { CapabilityProfile } from "./types";

function methodNameFromCapability(capabilityId: string, index: number): string {
    const sanitized = capabilityId
        .replace(/[^a-zA-Z0-9_]/g, "_")
        .replace(/^_+/, "")
        .replace(/_+$/, "");
    return sanitized ? `call_${sanitized}` : `call_capability_${index + 1}`;
}

function buildMethodBody(baseUrlExpr: string, method: string, pathValue: string): string {
    return [
        `const response = await fetch(${baseUrlExpr} + ${JSON.stringify(pathValue)}, {`,
        `  method: ${JSON.stringify(method)},`,
        "  headers: { ...this.authHeader, ...(request.headers ?? {}) },",
        "  body:",
        "    request.body !== undefined && request.body !== null",
        "      ? JSON.stringify(request.body)",
        "      : undefined,",
        "});",
        "",
        "const text = await response.text();",
        "let json: unknown = null;",
        "try {",
        "  json = text ? JSON.parse(text) : null;",
        "} catch {",
        "  json = text;",
        "}",
        "",
        "if (!response.ok) {",
        "  throw new Error(`SDK call failed (${response.status}) for ${request.path}: ${JSON.stringify(json)}`);",
        "}",
        "",
        "return json;",
    ].join("\n");
}

export function generateSdk(profile: CapabilityProfile): string {
    const methods = profile.capabilities
        .map((cap, index) => {
            const fnName = methodNameFromCapability(cap.capabilityId, index);
            const requestPath = cap.path;
            return `
  async ${fnName}(request: { path?: string; headers?: Record<string, string>; body?: unknown } = {}): Promise<unknown> {
    request.path = request.path ?? ${JSON.stringify(requestPath)};
${indent(buildMethodBody("this.baseUrl", cap.method, requestPath), 4)}
  }
`;
        })
        .join("\n");

    return `/* Auto-generated by probe-tool Phase 2 */
export class LegacyApiClient {
  constructor(
    private readonly baseUrl: string,
    private readonly authHeader: Record<string, string>
  ) {}
${methods}
}
`;
}

function indent(text: string, spaces: number): string {
    const pad = " ".repeat(spaces);
    return text
        .split("\n")
        .map((line) => (line.length > 0 ? `${pad}${line}` : line))
        .join("\n");
}

export function writeSdk(profile: CapabilityProfile): string {
    const outDir = path.resolve(process.cwd(), "generated-sdk", profile.customerId, profile.apiVersion);
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, "client.ts");
    fs.writeFileSync(outPath, generateSdk(profile), "utf-8");
    return outPath;
}
