import * as fs from "fs";
import * as path from "path";
import type { CapabilityProfile } from "./types";

function methodNameFromCapability(capabilityId: string, index: number): string {
    const sanitized = capabilityId
        .replace(/[^a-zA-Z0-9_]/g, "_")
        .replace(/^_+/, "")
        .replace(/_+$/, "");
    return sanitized ? `call_${sanitized}` : `call_capability_${index + 1}`;
}

function profileClassName(profile: CapabilityProfile): string {
    const raw = `${profile.customerId}_${profile.apiVersion}_${profile.apiBaseUrl}`
        .replace(/[^a-zA-Z0-9_]/g, "_")
        .replace(/_+/g, "_")
        .replace(/^_+|_+$/g, "");
    return `LegacyApiClient_${raw}`;
}

function capabilityMapLiteral(profile: CapabilityProfile): string {
    const rows = profile.capabilities
        .map((cap) =>
            `    ${JSON.stringify(cap.capabilityId)}: { method: ${JSON.stringify(cap.method)}, path: ${JSON.stringify(cap.path)} }`
        )
        .join(",\n");

    return `{
${rows}
  }`;
}

function methodBody(method: string): string {
    return [
        `const response = await fetch(this.baseUrl + (request.path ?? \"\"), {`,
        `  method: ${JSON.stringify(method)},`,
        "  headers: { ...this.authHeader, ...(request.headers ?? {}) },",
        "  body:",
        "    request.body !== undefined && request.body !== null",
        "      ? JSON.stringify(request.body)",
        "      : undefined,",
        "});",
        "",
        "const text = await response.text();",
        "let json: unknown = null;",
        "try {",
        "  json = text ? JSON.parse(text) : null;",
        "} catch {",
        "  json = text;",
        "}",
        "",
        "if (!response.ok) {",
        "  throw new Error('SDK call failed (' + response.status + ') for ' + (request.path ?? '') + ': ' + JSON.stringify(json));",
        "}",
        "",
        "return json;",
    ].join("\n");
}

function indent(text: string, spaces: number): string {
    const pad = " ".repeat(spaces);
    return text
        .split("\n")
        .map((line) => (line.length > 0 ? `${pad}${line}` : line))
        .join("\n");
}

export function generateSdk(profile: CapabilityProfile): string {
    const className = profileClassName(profile);
    const capabilityMap = capabilityMapLiteral(profile);

    const methods = profile.capabilities
        .map((cap, index) => {
            const fnName = methodNameFromCapability(cap.capabilityId, index);
            const requestPath = cap.path;
            return `
  async ${fnName}(request: { path?: string; headers?: Record<string, string>; body?: unknown } = {}): Promise<unknown> {
    request.path = request.path ?? ${JSON.stringify(requestPath)};
${indent(methodBody(cap.method), 4)}
  }
`;
        })
        .join("\n");

    return `/* Auto-generated by probe-tool Phase 3 */
export class ${className} {
  private readonly capabilityMap = ${capabilityMap};

  constructor(
    private readonly baseUrl: string,
    private readonly authHeader: Record<string, string>
  ) {}

  async callCapability(
    capabilityId: string,
    request: { path?: string; headers?: Record<string, string>; body?: unknown } = {}
  ): Promise<unknown> {
    const capability = this.capabilityMap[capabilityId as keyof typeof this.capabilityMap];
    if (!capability) {
      throw new Error('Unknown capabilityId: ' + capabilityId);
    }

    request.path = request.path ?? capability.path;
    const response = await fetch(this.baseUrl + request.path, {
      method: capability.method,
      headers: { ...this.authHeader, ...(request.headers ?? {}) },
      body:
        request.body !== undefined && request.body !== null
          ? JSON.stringify(request.body)
          : undefined,
    });

    const text = await response.text();
    let json: unknown = null;
    try {
      json = text ? JSON.parse(text) : null;
    } catch {
      json = text;
    }

    if (!response.ok) {
      throw new Error('SDK call failed (' + response.status + ') for ' + request.path + ': ' + JSON.stringify(json));
    }

    return json;
  }
${methods}
}
`;
}

export function writeSdk(profile: CapabilityProfile): string {
    const outDir = path.resolve(process.cwd(), "generated-sdk", profile.customerId, profile.apiVersion);
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, "client.ts");
    fs.writeFileSync(outPath, generateSdk(profile), "utf-8");
    return outPath;
}

function unifiedProfileLiteral(profile: CapabilityProfile): string {
    return `  {
    profileId: ${JSON.stringify(profile.profileId)},
    customerId: ${JSON.stringify(profile.customerId)},
    apiVersion: ${JSON.stringify(profile.apiVersion)},
    apiBaseUrl: ${JSON.stringify(profile.apiBaseUrl)},
    capabilities: ${JSON.stringify(
        profile.capabilities.map((cap) => ({
            capabilityId: cap.capabilityId,
            method: cap.method,
            path: cap.path,
        })),
        null,
        2
    ).replace(/^/gm, "    ").trimStart()}
  }`;
}

export function generateUnifiedSdk(profiles: CapabilityProfile[]): string {
    const serializedProfiles = profiles.map(unifiedProfileLiteral).join(",\n");

    return `/* Auto-generated by probe-tool Phase 3 */
type Capability = {
  capabilityId: string;
  method: string;
  path: string;
};

type InstallationProfile = {
  profileId: string;
  customerId: string;
  apiVersion: string;
  apiBaseUrl: string;
  capabilities: Capability[];
};

const PROFILES: InstallationProfile[] = [
${serializedProfiles}
];

export class InstallationClient {
  constructor(
    private readonly profile: InstallationProfile,
    private readonly authHeader: Record<string, string>
  ) {}

  listCapabilities(): Capability[] {
    return [...this.profile.capabilities];
  }

  async call(capabilityId: string, request: { path?: string; headers?: Record<string, string>; body?: unknown } = {}): Promise<unknown> {
    const capability = this.profile.capabilities.find((cap) => cap.capabilityId === capabilityId);
    if (!capability) {
      throw new Error('Unknown capabilityId: ' + capabilityId);
    }

    const targetPath = request.path ?? capability.path;
    const response = await fetch(this.profile.apiBaseUrl + targetPath, {
      method: capability.method,
      headers: { ...this.authHeader, ...(request.headers ?? {}) },
      body:
        request.body !== undefined && request.body !== null
          ? JSON.stringify(request.body)
          : undefined,
    });

    const text = await response.text();
    let json: unknown = null;
    try {
      json = text ? JSON.parse(text) : null;
    } catch {
      json = text;
    }

    if (!response.ok) {
      throw new Error('SDK call failed (' + response.status + ') for ' + targetPath + ': ' + JSON.stringify(json));
    }

    return json;
  }
}

export class ProbeSdk {
  private readonly profiles = PROFILES;

  forInstallation(params: {
    customerId: string;
    apiVersion: string;
    apiBaseUrl?: string;
    authHeader: Record<string, string>;
  }): InstallationClient {
    const profile = this.profiles.find((item) =>
      item.customerId === params.customerId &&
      item.apiVersion === params.apiVersion &&
      (params.apiBaseUrl ? item.apiBaseUrl === params.apiBaseUrl : true)
    );

    if (!profile) {
      throw new Error('No profile found for customer=' + params.customerId + ', version=' + params.apiVersion + ', baseUrl=' + (params.apiBaseUrl ?? '<any>'));
    }

    return new InstallationClient(profile, params.authHeader);
  }

  listProfiles(): InstallationProfile[] {
    return [...this.profiles];
  }
}

export function createProbeSdk(): ProbeSdk {
  return new ProbeSdk();
}
`;
}

export function writeUnifiedSdk(profiles: CapabilityProfile[]): string {
    const outDir = path.resolve(process.cwd(), "generated-sdk");
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, "index.ts");
    fs.writeFileSync(outPath, generateUnifiedSdk(profiles), "utf-8");
    return outPath;
}
