/* Auto-generated by probe-tool Phase 3 */
type Capability = {
  capabilityId: string;
  method: string;
  path: string;
};

type InstallationProfile = {
  profileId: string;
  customerId: string;
  apiVersion: string;
  apiBaseUrl: string;
  capabilities: Capability[];
};

const PROFILES: InstallationProfile[] = [
  {
    profileId: "cust_a__v1.1__http://localhost:4011",
    customerId: "cust_a",
    apiVersion: "v1.1",
    apiBaseUrl: "http://localhost:4011",
    capabilities: [
      {
        "capabilityId": "goal_1_step_1",
        "method": "GET",
        "path": "/api/{{apiVersion}}/orders/template"
      },
      {
        "capabilityId": "goal_1_step_2",
        "method": "PUT",
        "path": "/api/{{apiVersion}}/orders/ord-{{runId}}"
      },
      {
        "capabilityId": "goal_2_step_1",
        "method": "POST",
        "path": "/api/{{apiVersion}}/invoices"
      }
    ]
  },
  {
    profileId: "cust_a__v1.1__http://localhost:4012",
    customerId: "cust_a",
    apiVersion: "v1.1",
    apiBaseUrl: "http://localhost:4012",
    capabilities: [
      {
        "capabilityId": "goal_1_step_preflight",
        "method": "POST",
        "path": "/api/v1.1/orders/preflight"
      },
      {
        "capabilityId": "goal_1_step_1",
        "method": "GET",
        "path": "/api/v1.1/orders/template"
      },
      {
        "capabilityId": "goal_1_step_2",
        "method": "POST",
        "path": "/api/v1.1/orders/{{runId}}-order-{{now}}"
      },
      {
        "capabilityId": "goal_2_step_1",
        "method": "PUT",
        "path": "/api/{{apiVersion}}/invoices"
      },
      {
        "capabilityId": "goal_3_step_1",
        "method": "GET",
        "path": "/api/v1.1/expenses/summary"
      }
    ]
  },
  {
    profileId: "cust_a__v1.1__http://localhost:4013",
    customerId: "cust_a",
    apiVersion: "v1.1",
    apiBaseUrl: "http://localhost:4013",
    capabilities: [
      {
        "capabilityId": "goal_1_step_preflight",
        "method": "POST",
        "path": "/api/v1.1/orders/preflight"
      },
      {
        "capabilityId": "goal_1_step_1",
        "method": "GET",
        "path": "/api/v1.1/orders/template"
      },
      {
        "capabilityId": "goal_1_step_2",
        "method": "POST",
        "path": "/api/v1.1/orders/{{runId}}-order"
      },
      {
        "capabilityId": "goal_2_step_1",
        "method": "PUT",
        "path": "/api/v1.1/invoices"
      },
      {
        "capabilityId": "goal_3_step_1",
        "method": "GET",
        "path": "/api/v1.1/expenses/summary"
      }
    ]
  },
  {
    profileId: "cust_a__v1.2__http://localhost:4011",
    customerId: "cust_a",
    apiVersion: "v1.2",
    apiBaseUrl: "http://localhost:4011",
    capabilities: [
      {
        "capabilityId": "goal_1_step_1",
        "method": "GET",
        "path": "/api/v1.2/orders/template"
      },
      {
        "capabilityId": "goal_1_step_2",
        "method": "PUT",
        "path": "/api/v1.2/orders/ord_{{runId}}"
      },
      {
        "capabilityId": "goal_2_step_1",
        "method": "POST",
        "path": "/api/v1.2/invoices"
      }
    ]
  },
  {
    profileId: "cust_b__v1.1__http://localhost:4011",
    customerId: "cust_b",
    apiVersion: "v1.1",
    apiBaseUrl: "http://localhost:4011",
    capabilities: [
      {
        "capabilityId": "goal_1_step_1",
        "method": "GET",
        "path": "/api/v1.1/orders/template"
      },
      {
        "capabilityId": "goal_1_step_2",
        "method": "PUT",
        "path": "/api/v1.1/orders/{{runId}}-order"
      },
      {
        "capabilityId": "goal_2_step_1",
        "method": "POST",
        "path": "/api/v1.1/invoices"
      },
      {
        "capabilityId": "goal_3_step_1",
        "method": "GET",
        "path": "/api/v1.1/expenses/summary"
      }
    ]
  }
];

export class InstallationClient {
  constructor(
    private readonly profile: InstallationProfile,
    private readonly authHeader: Record<string, string>
  ) {}

  listCapabilities(): Capability[] {
    return [...this.profile.capabilities];
  }

  async call(capabilityId: string, request: { path?: string; headers?: Record<string, string>; body?: unknown } = {}): Promise<unknown> {
    const capability = this.profile.capabilities.find((cap) => cap.capabilityId === capabilityId);
    if (!capability) {
      throw new Error('Unknown capabilityId: ' + capabilityId);
    }

    const targetPath = request.path ?? capability.path;
    const response = await fetch(this.profile.apiBaseUrl + targetPath, {
      method: capability.method,
      headers: { ...this.authHeader, ...(request.headers ?? {}) },
      body:
        request.body !== undefined && request.body !== null
          ? JSON.stringify(request.body)
          : undefined,
    });

    const text = await response.text();
    let json: unknown = null;
    try {
      json = text ? JSON.parse(text) : null;
    } catch {
      json = text;
    }

    if (!response.ok) {
      throw new Error('SDK call failed (' + response.status + ') for ' + targetPath + ': ' + JSON.stringify(json));
    }

    return json;
  }
}

export class ProbeSdk {
  private readonly profiles = PROFILES;

  forInstallation(params: {
    customerId: string;
    apiVersion: string;
    apiBaseUrl?: string;
    authHeader: Record<string, string>;
  }): InstallationClient {
    const profile = this.profiles.find((item) =>
      item.customerId === params.customerId &&
      item.apiVersion === params.apiVersion &&
      (params.apiBaseUrl ? item.apiBaseUrl === params.apiBaseUrl : true)
    );

    if (!profile) {
      throw new Error('No profile found for customer=' + params.customerId + ', version=' + params.apiVersion + ', baseUrl=' + (params.apiBaseUrl ?? '<any>'));
    }

    return new InstallationClient(profile, params.authHeader);
  }

  listProfiles(): InstallationProfile[] {
    return [...this.profiles];
  }
}

export function createProbeSdk(): ProbeSdk {
  return new ProbeSdk();
}
